name: Pages PR Preview Deploy

on:
  workflow_run:
    workflows: ["Pages PR Build"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read          # needed to download artifacts from another run
  pull-requests: write   # to comment the preview URL on the PR

concurrency:
  group: "pages-preview"
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Download artifact from PR build
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: pages-pr-site
          path: ./_site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages (preview)
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - name: Comment preview link on PR
        if: ${{ github.event.workflow_run.pull_requests[0].number != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests?.[0];
            if (!pr) return;
            const prNumber = pr.number;
            const url = '${{ steps.deploy.outputs.page_url }}';
            const body = `🔍 **Docs preview ready:** ${url}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            });
